### ISSUE TITLE
Error: exception: Client id cannot be nil

### ISSUE THREAD

**Issue by nordickiwi** [sensu-plugins/sensu-plugins-azurerm#12]
Multiple attempts return same error.

`# check-azurerm-cores-d-usage.rb -t "my_data" -c "my_data" -S "my_data" -s "my_data" -l "SoutheastAsia" -w 80 -c 90`
Error: exception: Client id cannot be nil
CheckAzureRMCoresDUsage CRITICAL

Using Id's from following this instruction - https://docs.bmc.com/docs/cloudlifecyclemanagement/46/setting-up-a-tenant-id-client-id-and-client-secret-for-azure-resource-manager-provisioning-669202145.html

Any help in sorting this is appreciated.

**Comment by majormoses** [comment]
@tombuildsstuff any ideas?

**Comment by falmada** [comment]
Just saw this, running into same issue, tried both with -c and -client_id as per documentation. This is for sensu-go. 

```
type: CheckConfig
api_version: core/v2
metadata:
  name: check-azurerm-core-usage
  namespace: default
spec:
  command: check-azurerm-core-usage.rb
    - -tenant "edited"
    - -client_id "edited"
    - -client_secret "edited"
    - -subscription "edited"
    - -location "edited"
    - -warning_percentage 80
    - -critical_percentage 90
  interval: 30
  publish: true
  round_robin: true
  runtime_assets:
  - sensu-plugins-azurerm
  - sensu-ruby-runtime
  subscriptions:
  - proxy
```

Checked the code for check-azurerm-core-usage.rb and found below:
```
option :client_id,
         description: 'ARM Client ID. Either set ENV[\'ARM_CLIENT_ID\'] or provide it as an option',
         short: '-c ID',
         long: '--client ID',
         default: ENV['ARM_CLIENT_ID']
```
So in theory -c, -client_id or --client should work, but unfortunately none of them do.

Was anyone able to get this working?

Thanks!
